SELECT c.TABLE_NAME
	 , ISNULL([KEY], '') [KEY]
	 , c.COLUMN_NAME
	 , CASE 
		WHEN DATA_TYPE LIKE '%CHAR%' OR DATA_TYPE LIKE '%BINARY%'
			THEN CONCAT(DATA_TYPE,'(', IIF(CHARACTER_MAXIMUM_LENGTH = -1, 'MAX', CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR)), ')')
		WHEN DATA_TYPE = 'DECIMAL'
			THEN CONCAT(DATA_TYPE, '(', NUMERIC_PRECISION, ',', NUMERIC_SCALE, ')')
		ELSE DATA_TYPE
	 END DATA_TYPE
	 , IIF(IS_NULLABLE = 'YES', '-', '+') AS [REQUIRED]
	 , ISNULL(COLUMN_DEFAULT, '') AS COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS c LEFT JOIN
	 (SELECT k.TABLE_NAME
		 , IIF(t.CONSTRAINT_TYPE LIKE 'PRIMARY%', 'PK', 'FK') [KEY]
		 , COLUMN_NAME
	 FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE k JOIN
		  INFORMATION_SCHEMA.TABLE_CONSTRAINTS t ON k.CONSTRAINT_NAME = t.CONSTRAINT_NAME) k
	 ON k.TABLE_NAME = c.TABLE_NAME AND k.COLUMN_NAME = c.COLUMN_NAME
WHERE c.TABLE_NAME IN (SELECT TABLE_NAME
					   FROM INFORMATION_SCHEMA.TABLES
						 WHERE TABLE_TYPE <> 'VIEW' AND TABLE_TYPE <> 'sysdiagrams')
	 



--SELECT k.TABLE_NAME
--	 , IIF(t.CONSTRAINT_TYPE LIKE '%PRIMARY', 'PK', 'FK') [KEY]
--	 , COLUMN_NAME
--FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE k JOIN
--	 INFORMATION_SCHEMA.TABLE_CONSTRAINTS t ON k.CONSTRAINT_NAME = t.CONSTRAINT_NAME
--ORDER BY k.TABLE_NAME, COLUMN_NAME